### PR TITLE
Unenrol command

### LINKED ISSUE #33: As a beginner user, I can remove a member from an event
... so that, I can amend adding the wrong person to an event.

### LINKED ISSUE #126: Make delete member of event functionality

### PR DESCRIPTION
**Pull request by SelwynAng**
Closes #126, #33 

- Created `UnenrolCommand`, `UnenrolCommandParser`
- Created tests for the above classes
- Created `findEnrolmentFromList()` method in the `ModelManager` class
- Created new `HandledParseException` class
- Created new classes for test purposes, namely `TypicalHours` and `TypicalRemarks`

### CODE REVIEW

File: src/main/java/seedu/ccacommander/logic/commands/UnenrolCommand.java [hunk 1]
```diff
@@ -0,0 +1,127 @@
...
+            if (memberName.equals(selectedMemberName) && eventName.equals(selectedEventName)) {
+                break;
+            }
+        }
+
+        if (selectedEnrolment == null) {
+            throw new EnrolmentNotFoundException();
+        } else {
+            return selectedEnrolment;
+        }
```
Comment (wr1159) [inline src/main/java/seedu/ccacommander/logic/commands/UnenrolCommand.java]: Would it make sense to move this function elsewhere maybe to Model since this seems quite reusable.

File: src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java [hunk 2]
```diff
@@ -0,0 +1,157 @@
...
+    }
+
+    /**
+     * Updates {@code model}'s filtered enrolment list to show no one.
+     */
+    private void showNoEnrolment(Model model) {
+        model.updateFilteredEnrolmentList(p -> false);
+
+        assertTrue(model.getFilteredEnrolmentList().isEmpty());
+    }
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java]: What is the use of this here?

File: src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+
+        // invalid value followed by valid value
+
+        // invalid member index
+        assertParseFailure(parser, INVALID_MEMBER_INDEX_DESC + validExpectedEnrolmentString,
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_MEMBER));
+
+        // invalid event index
+        assertParseFailure(parser, INVALID_EVENT_INDEX_DESC + validExpectedEnrolmentString,
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_EVENT));
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java]: Aren't these repeated values also since we have an invalid member then a valid member and a valid event?

File: src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java [hunk 4]
```diff
@@ -0,0 +1,142 @@
...
+
+        // valid value followed by invalid value
+
+        // invalid member index
+        assertParseFailure(parser, validExpectedEnrolmentString + INVALID_MEMBER_INDEX_DESC,
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_MEMBER));
+
+        // invalid event index
+        assertParseFailure(parser, validExpectedEnrolmentString + INVALID_EVENT_INDEX_DESC,
+                Messages.getErrorMessageForDuplicatePrefixes(PREFIX_EVENT));
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java]: same here

File: src/main/java/seedu/ccacommander/logic/parser/exceptions/HandledParseException.java
Comment (wr1159) [inline src/main/java/seedu/ccacommander/logic/parser/exceptions/HandledParseException.java:1]: I am still kind of confused on how this works, can you give an example?

**Review by wr1159 — CHANGES_REQUESTED** [review]
LGTM overall, a few comments for you to look through

File: src/main/java/seedu/ccacommander/logic/commands/UnenrolCommand.java (hunk 1 above)
Comment (SelwynAng) [reply src/main/java/seedu/ccacommander/logic/commands/UnenrolCommand.java]: Good suggestion, will move this to the `ModelManager` class.

File: src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java (hunk 2 above)
Comment (SelwynAng) [reply src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java]: I saw that the `DeleteMemberCommand` and `DeleteEventCommand` also had this test so I reckon that `UnenrolCommand` will require this test too as it involves the deletion of an entity. Should I remove this test case? I'm thinking that this test case is meant to check if the`updateFilteredEnrolmentList` method is working as intended.

File: src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java (hunk 3 above)
Comment (SelwynAng) [reply src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java]: Makes sense, will make the change!

File: src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java (hunk 4 above)
Comment (SelwynAng) [reply src/test/java/seedu/ccacommander/logic/parser/UnenrolCommandParserTest.java]: Makes sense, will make the change!

File: src/main/java/seedu/ccacommander/logic/parser/exceptions/HandledParseException.java
Comment (SelwynAng) [reply src/main/java/seedu/ccacommander/logic/parser/exceptions/HandledParseException.java:1]: So for example, I have this code block:

```
public void methodA() throws ParseException {
    try {
        // Some code that may throw ParseException that has a message "This is the original exception!"
    } catch (ParseException pe) {
        throw new ParseException("This is a rethrown exception!");
    }
}

public void methodB() {
    try {
        methodA();
    } catch (ParseException pe) {
        // This block will catch the original ParseException instead of the new rethrown ParseException.
        System.out.println(pe.getMessage()); // "This is the original exception!" will be printed out, which not what I want :(
    }
}
```

In order for me to catch the rethrown exception and actually print out the rethrown exception's message, "This is a rethrown exception!", I have to make a subtype for the rethrown exception. This is needed for one of the test cases for `UnenrolCommandParse`, namely `parse_excessArguments_failure` test case.  Is there a better way to circumvent this @wr1159 ?

File: src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java (hunk 2 above)
Comment (wr1159) [reply src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java]: Ah I think right now it is a function and not a test since it's lacking an @test

Comment (SelwynAng) [reply src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java]: Alright, will add in the missing annotation!

File: src/test/java/seedu/ccacommander/testutil/TypicalHours.java [hunk 5]
```diff
@@ -0,0 +1,14 @@
...
+import seedu.ccacommander.model.enrolment.Hours;
+
+/**
+ * A utility class containing a list of {@code Hours} objects to be used in tests.
+ */
+public class TypicalHours {
+    public static final Hours HOURS_ZERO = new Hours("0");
+    public static final Hours HOURS_ONE = new Hours("1");
+    public static final Hours HOURS_TEN = new Hours("10");
+    public static final Hours HOURS_MAX = new Hours("2147483647");
```
Comment (ph-nathan) [inline src/test/java/seedu/ccacommander/testutil/TypicalHours.java:12]: since only Hours_zero is used for the tests in this PR, maybe we can keep in mind to use the other three in future test cases or remove the other ones. I think we sometimes have a habit of introducing more variables than needed in tests so it might clutter the test files.

**Review by ph-nathan — APPROVED** [review]
LGTM, generaly a good effort PR. Grate job selwynnn :D

File: src/test/java/seedu/ccacommander/testutil/TypicalHours.java (hunk 5 above)
Comment (SelwynAng) [reply src/test/java/seedu/ccacommander/testutil/TypicalHours.java:12]: Agreed! But we still have time to clear up the test files and streamline our test cases in v1.4, so no rush for now.

File: src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java [hunk 6]
```diff
@@ -0,0 +1,197 @@
...
+    /**
+     * Updates {@code model}'s filtered enrolment list to show no one.
+     */
+    @Test
+    private void showNoEnrolment(Model model) {
+        model.updateFilteredEnrolmentList(p -> false);
+
+        assertTrue(model.getFilteredEnrolmentList().isEmpty());
+    }
+}
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/commands/UnenrolCommandTest.java:197]: I would recommend to remove this as it seems to be testing more for model instead of unenrolCommand unless it's used.

**Review by wr1159 — APPROVED** [review]
LGTM
