### PR TITLE
Fix edit command bug

### LINKED ISSUE #190: Edit Member/Event Command has issues
When we have 2 enrolments with the same event, but different member name.

Commands to recreate

enrol m/1 e/1 h/0 r/r
enrol m/2 e/1 h/0 r/r
editMember 1 n/turtle

### PR DESCRIPTION
**Pull request by ph-nathan**
Closes #190

What have you done in this PR?
* Fix edit commands  
* Abstract out implementation details for editing enrolments

Dev Testing Steps / Screenshots

### CODE REVIEW

File: src/main/java/seedu/ccacommander/model/ModelManager.java [hunk 1]
```diff
@@ -190,6 +190,48 @@ public static Enrolment findEnrolmentFromList(List<Enrolment> lastShownEnrolment
...
+        List<Enrolment> enrolmentList = model.getFilteredEnrolmentList();
+        for (Enrolment enrolment: enrolmentList) {
+            if (enrolment.getEventName().equals(prevName)) {
+                Enrolment editedEnrolment = new Enrolment(enrolment.getMemberName(), newName,
+                        enrolment.getHours(), enrolment.getRemark());
+                model.setEnrolment(enrolment, editedEnrolment);
+            }
+        }
+    }
+
```
Comment (wr1159) [inline src/main/java/seedu/ccacommander/model/ModelManager.java]: Hmm, any reasoning for this to be a static function? I was thinking that since modelManager implements Model, we can have the modelManager call the function instead of passing in the model as a parameter.

**Review by wr1159 — APPROVED** [review]
Left a comment about the modelManager function being static, other than that LGTM

File: src/main/java/seedu/ccacommander/model/ModelManager.java (hunk 1 above)
Comment (ph-nathan) [reply src/main/java/seedu/ccacommander/model/ModelManager.java]: okay I will do that :')

**Review by wr1159 — APPROVED** [review]
LGTM now

File: src/test/java/seedu/ccacommander/logic/commands/CreateEventCommandTest.java [hunk 2]
```diff
@@ -175,6 +177,17 @@ public void setEvent(Event event, Event editedEvent) {
         public void createEnrolment(Enrolment enrolment) {
             throw new AssertionError("This method should not be called.");
         }
+
```
Comment (dylkaw) [inline src/test/java/seedu/ccacommander/logic/commands/CreateEventCommandTest.java:180]: Just a nit can this line be removed?
```suggestion
```

**Review by dylkaw — APPROVED** [review]
Very small nit, LGTM!
