### PR TITLE
Fix edit enrolment

### LINKED ISSUE #205: [PE-D][Tester A] GUI does not update after editEnrolment command
After passing the editEnrolment command in this screenshot, the GUI did not update for the event. Only after returning to the list and using viewMember again, could you see the change.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: EricXiong420/ped#4

### PR DESCRIPTION
**Pull request by ph-nathan**
Closes #205 

What have you done in this PR?
* Fix edit enrolment to allow edited enrolment data to be displayed automatically in UI by tracking the previous predicate used by updateFilteredEventList and updateFilteredMemberList.
* Add testcases for the new methods

Dev Testing Steps / Screenshots
image

### CODE REVIEW

**Comment by wr1159** [comment]
Putting on hold until prof damith replies us in https://github.com/nus-cs2103-AY2324S1/forum/issues/370

File: src/test/java/seedu/ccacommander/logic/commands/CreateMemberCommandTest.java [hunk 1]
```diff
@@ -215,6 +215,7 @@ public ObservableList<Member> getFilteredMemberList() {
             throw new AssertionError("This method should not be called.");
         }
 
+
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/commands/CreateMemberCommandTest.java]: slight nit but can we remove this empty line to standardise our spacing?

File: src/test/java/seedu/ccacommander/model/ModelManagerTest.java
Comment (wr1159) [inline src/test/java/seedu/ccacommander/model/ModelManagerTest.java:1]: Do you want to include a test where users do change the predicate and the last predicate does change?

**Review by wr1159 — COMMENTED** [review]
LGTM overall, just 2 comments to look through, will approve once addressed (either through code change / comment)

File: src/test/java/seedu/ccacommander/model/ModelManagerTest.java
Comment (ph-nathan) [reply src/test/java/seedu/ccacommander/model/ModelManagerTest.java:1]: Oh LOL i forgot to push that sorry :')

**Review by dylkaw — APPROVED** [review]
LGTM!
