### PR TITLE
Fix edit command

### LINKED ISSUE #128: Fix `edit` command
Once we have implemented the storing/loading of attendance, every time we `edit` a member or event name, we need to iterate through the attendance list and update all `memberName` or `eventName` fields of the attendance object

### PR DESCRIPTION
**Pull request by ph-nathan**
Closes #128 

What have you done in this PR?
* Update editMemberCommand and editEventCommand files to also update corresponding Enrolment object when names are modified
* Added setEnrolment to LogicManager
* Modified tests to match current behaviour of editCommands
* Add test for enrolment related functions in LogicManager

Dev Testing Steps / Screenshots

### CODE REVIEW

File: src/main/java/seedu/ccacommander/logic/commands/EditEventCommand.java [hunk 1]
```diff
@@ -81,6 +82,21 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_EVENT);
         }
 
+
+        Name prevName = eventToEdit.getName();
+        Name newName = editedEvent.getName();
+        // If event's name is edited, the corresponding enrolment objects are edited also
+        if (!prevName.equals(newName)) {
+            List<Enrolment> enrolmentList = model.getFilteredEnrolmentList();
```
Comment (wr1159) [inline src/main/java/seedu/ccacommander/logic/commands/EditEventCommand.java]: if we use getFilteredEnrolmentList() here will we only edit the currently filteredEnrolmentList?

File: src/main/java/seedu/ccacommander/logic/commands/EditMemberCommand.java [hunk 2]
```diff
@@ -87,6 +88,20 @@ public CommandResult execute(Model model) throws CommandException {
             throw new CommandException(MESSAGE_DUPLICATE_MEMBER);
         }
 
+        Name prevName = memberToEdit.getName();
+        Name newName = editedMember.getName();
+        // If member's name is edited, the corresponding enrolment objects are edited also
+        if (!prevName.equals(newName)) {
+            List<Enrolment> enrolmentList = model.getFilteredEnrolmentList();
```
Comment (wr1159) [inline src/main/java/seedu/ccacommander/logic/commands/EditMemberCommand.java]: Same here

File: src/test/java/seedu/ccacommander/logic/commands/EditEventCommandTest.java [hunk 3]
```diff
@@ -24,10 +26,14 @@
...
 import seedu.ccacommander.model.ModelManager;
 import seedu.ccacommander.model.UserPrefs;
+import seedu.ccacommander.model.enrolment.Enrolment;
 import seedu.ccacommander.model.event.Event;
+import seedu.ccacommander.model.shared.Name;
 import seedu.ccacommander.testutil.EditEventDescriptorBuilder;
 import seedu.ccacommander.testutil.EventBuilder;
 
+
+
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/commands/EditEventCommandTest.java]: Nit but do you think we can remove these 2 spaces?

File: src/test/java/seedu/ccacommander/model/ModelManagerTest.java [hunk 4]
```diff
@@ -194,6 +196,33 @@ public void updateEvents() {
...
+    @Test
+    public void hasEnrolment_enrolmentNotInCcaCommander_returnsFalse() {
+        assertFalse(modelManager.hasEnrolment(ALICE_AURORA));
+    }
+
+    @Test
+    public void hasEnrolment_enrolmentInCcaCommander_returnsTrue() {
+        modelManager.createEnrolment(ALICE_AURORA);
+        assertTrue(modelManager.hasEnrolment(ALICE_AURORA));
+    }
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/model/ModelManagerTest.java:222]: Just to confirm, these have nothing to do with the new function written right but are meant to serve as additional test cases?

**Review by wr1159 — COMMENTED** [review]
Left a few comments but LGTM overall

File: src/main/java/seedu/ccacommander/logic/commands/EditEventCommand.java (hunk 1 above)
Comment (dylkaw) [reply src/main/java/seedu/ccacommander/logic/commands/EditEventCommand.java]: Perhaps an idea could be to use a predicate to compare the names in order to update the filteredEnrolmentList with the Enrolments containing the specified eventNames?

File: src/main/java/seedu/ccacommander/logic/commands/EditMemberCommand.java (hunk 2 above)
Comment (dylkaw) [reply src/main/java/seedu/ccacommander/logic/commands/EditMemberCommand.java]: Similar suggestion as above.

**Review by dylkaw — COMMENTED** [review]
Some comments on filtering the enrolmentList.

File: src/test/java/seedu/ccacommander/model/ModelManagerTest.java (hunk 4 above)
Comment (ph-nathan) [reply src/test/java/seedu/ccacommander/model/ModelManagerTest.java:222]: yep, you are correct!

File: src/test/java/seedu/ccacommander/logic/commands/EditEventCommandTest.java [hunk 5]
```diff
@@ -70,7 +94,26 @@ public void execute_someFieldsSpecifiedUnfilteredList_success() {
...
+            // update filtered enrolment list to contain only the enrolments that has event of previous name
+            expectedModel.updateFilteredEnrolmentList(new EnrolmentContainsEventPredicate(prevName));
+            List<Enrolment> enrolmentsToEditList = model.getFilteredEnrolmentList();
+            model.updateFilteredEnrolmentList(Model.PREDICATE_SHOW_ALL_ENROLMENTS);
+            expectedModel.updateFilteredEnrolmentList(Model.PREDICATE_SHOW_ALL_ENROLMENTS);
+            for (Enrolment enrolment : enrolmentsToEditList) {
+                Enrolment editedEnrolment = new Enrolment(enrolment.getMemberName(), newName,
+                            enrolment.getHours(), enrolment.getRemark());
+                model.setEnrolment(enrolment, editedEnrolment);
+                expectedModel.setEnrolment(enrolment, editedEnrolment);
```
Comment (wr1159) [inline src/test/java/seedu/ccacommander/logic/commands/EditEventCommandTest.java]: This test doesn't do much since you're doing things on the actual model and then the expected model, it will definitely be the same. Instead I think you should either abstract to a function or just use hasEnrolment to check whether the enrolment exists. The latter is better

**Review by wr1159 — APPROVED** [review]
LGTM now

**Review by dylkaw — APPROVED** [review]
LGTM!
